version: '3.8'

services:
  postgresql:
    image: postgres
    environment:
      DB_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      locale:
        ipv4_address: 177.77.0.77
    volumes:
      - pgdata:/var/lib/postgresql/data
  #  entrypoint: [ "/bin/bash", "-c", "echo \"
  #                                    CREATE TABLE log_table
  #                                    (
  #                                        id_log_table     SERIAL PRIMARY KEY,
  #                                        log_uuid         VARCHAR(64),
  #                                        log_datetime     TIMESTAMP,
  #                                        ip_address       VARCHAR(32),
  #                                        http_method      VARCHAR(32),
  #                                        uri              VARCHAR(256),
  #                                        http_status_code INTEGER
  #                                    );
  #                                    \" | psql -U \"$DB_USER\"" ]

  webapi:
    build:
      context: ./
      dockerfile: ./webapi/Dockerfile
    networks:
      locale:
        ipv4_address: 177.77.0.78
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  cliapi:
    build:
      context: ./
      dockerfile: ./cliapi/Dockerfile
    environment:
      THREADS: 4
      DELAY: 1000
    volumes:
      - ~/cliapi_client.log:/app/client.log
    networks:
      - locale
    depends_on:
      - webapi

  bgproc:
    build:
      context: ./
      dockerfile: ./bgproc/Dockerfile
    volumes:
      - ~/bgproc_data.txt:/app/data.txt
    networks:
      - locale
    depends_on:
      - postgresql
      - webapi

networks:
  locale:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 177.77.0.0/24
          gateway: 177.77.0.1
          ip_range: 177.77.0.2/24

volumes:
  pgdata:
